os: linux
dist: bionic
language: php

services:
  - elasticsearch

php:
  - 8.1

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update
  - echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enable_cli = '1'" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - wget -O local-php-security-checker https://github.com/fabpot/local-php-security-checker/releases/download/v2.0.3/local-php-security-checker_2.0.3_linux_amd64
  - chmod +x local-php-security-checker

install:
  - composer install

before_script:
  - sleep 10

jobs:
  include:
    - script:
      - ./local-php-security-checker
      - ./bin/console lint:yaml config
      - ./vendor/bin/parallel-lint --exclude app --exclude vendor .
      - ./vendor/bin/phpcs -s src tests
      - ./vendor/bin/deptrac
      - ./vendor/bin/phpunit --testsuite Unit -c phpunit.xml.dist
    - script:
      - ./vendor/bin/phpunit --testsuite Integration -c phpunit.xml.dist

notifications:
  email: false
