monolog:
    handlers:
        main:
            type:  rotating_file
            path:  '%env(LOG_FILE_PATH)%'
            level: notice
            max_files: 10
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
