parameters:
    monolog.level: '%env(LOG_LEVEL)%'
monolog:
    handlers:
        main:
            type:  stream
            path:  '%env(LOG_FILE_PATH)%'
            level: '%monolog.level%'
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
