parameters:
    api_version: 'v1'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Adshares\AdSelect\UI\:
        resource: '../src/UI/*'
        exclude: '../src/UI/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Adshares\AdSelect\UI\Controller\:
        resource: '../src/UI/Controller'
        tags: ['controller.service_arguments']

    Adshares\AdSelect\UI\Command\CreateIndex:
        arguments:
            $client: '@Adshares\AdSelect\Infrastructure\ElasticSearch\Client'

    Adshares\AdSelect\Infrastructure\ElasticSearch\Client:
        arguments:
            $hosts:
                - { host: '%env(ES_HOST)%', port: '%env(ES_PORT)%' }
            $logger: '@logger'

    Adshares\AdSelect\Infrastructure\ElasticSearch\Service\ElasticSearchCampaignUpdater:
        arguments:
            $client: '@Adshares\AdSelect\Infrastructure\ElasticSearch\Client'
            $bulkLimit: 500

    Adshares\AdSelect\Infrastructure\ElasticSearch\Service\EventCollector:
        arguments:
            $client: '@Adshares\AdSelect\Infrastructure\ElasticSearch\Client'
            $bulkLimit: 500
            $keywordIntersectThreshold: 10

    Adshares\AdSelect\Infrastructure\ElasticSearch\Service\EventFinder:
        arguments:
            $client: '@Adshares\AdSelect\Infrastructure\ElasticSearch\Client'
            $logger: '@logger'

    Adshares\AdSelect\Infrastructure\ElasticSearch\Service\BannerFinder:
        arguments:
            $client: '@Adshares\AdSelect\Infrastructure\ElasticSearch\Client'
            $expInterval: 10
            $expThreshold: 50
            $logger: '@logger'

    Adshares\AdSelect\UI\EventListener\ApiExceptionListenerSubscriber:
        arguments:
            $env: '%env(APP_ENV)%'
            $logger: '@logger'
        tags:
            - { name: kernel.event_subscriber }

    Adshares\AdSelect\UI\Controller\CampaignController:
        public: true
        autowire: false
        autoconfigure: false
        arguments:
            $campaignUpdater: '@Adshares\AdSelect\Infrastructure\ElasticSearch\Service\ElasticSearchCampaignUpdater'
            $bannerFinder: '@Adshares\AdSelect\Infrastructure\ElasticSearch\Service\BannerFinder'
            $logger: '@logger'

    Adshares\AdSelect\UI\Controller\EventController:
        public: true
        autowire: false
        autoconfigure: false
        arguments:
            $eventCollector: '@Adshares\AdSelect\Infrastructure\ElasticSearch\Service\EventCollector'
            $eventFinder: '@Adshares\AdSelect\Infrastructure\ElasticSearch\Service\EventFinder'
            $logger: '@logger'
