parameters:
    api_version: 'v1'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Adshares\AdSelect\UI\:
        resource: '../src/UI/*'
        exclude: '../src/UI/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Adshares\AdSelect\UI\Controller\:
        resource: '../src/UI/Controller'
        tags: ['controller.service_arguments']

    Adshares\AdSelect\UI\Command\CreateIndex:
        arguments:
            $client: '@Adshares\AdSelect\Infrastructure\ElasticSearch\Client'

    Adshares\AdSelect\Infrastructure\ElasticSearch\Client:
        arguments:
            $hosts: { host: '%env(ES_HOST)%', port: '%env(ES_PORT' }

    Adshares\AdSelect\Infrastructure\ElasticSearch\Service\ElasticSearchCampaignUpdater:
        arguments:
            $client: '@Adshares\AdSelect\Infrastructure\ElasticSearch\Client'

    Adshares\AdSelect\UI\EventListener\ApiExceptionListenerSubscriber:
        arguments:
            $env: '%env(APP_ENV)%'
        tags:
            - { name: kernel.event_subscriber }

    Adshares\AdSelect\UI\Controller\CampaignController:
        public: true
        autowire: false
        autoconfigure: false
        arguments:
            $campaignUpdater: '@Adshares\AdSelect\Infrastructure\ElasticSearch\Service\ElasticSearchCampaignUpdater'
