parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Adshares\AdSelect\UI\:
        resource: '../src/UI/*'
        exclude: '../src/UI/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Adshares\AdSelect\UI\Controller\:
        resource: '../src/UI/Controller'
        tags: ['controller.service_arguments']

    Adshares\AdSelect\UI\Command\CreateIndex:
        arguments:
            $client: '@Adshares\AdSelect\Infrastructure\Client\ElasticSearch'

    Adshares\AdSelect\Infrastructure\Client\ElasticSearch:
        arguments:
            $hosts: { host: '%env(ES_HOST)%', port: '%env(ES_PORT' }
