import os

#: Wait with recalculation of scores.
RECALCULATE_TASK_SECONDS_INTERVAL = int(os.getenv('ADSELECT_RECALCULATE_TASK_SECONDS_INTERVAL'))

#: Limit new banners.
NEW_BANNERS_IMPRESSION_CUTOFF = int(os.getenv('ADSELECT_NEW_BANNERS_IMPRESSION_CUTOFF'))
